// [left, right] concept pairs spanning a 0–100 spectrum.
export const SPECTRUMS: [string, string][] = [
  ['Cheap', 'Expensive'], ['Overrated', 'Underrated'], ['Boring', 'Exciting'], ['Cold', 'Hot'],
  ['Small', 'Large'], ['Quiet', 'Loud'], ['Ugly', 'Beautiful'], ['Simple', 'Complicated'],
  ['Slow', 'Fast'], ['Old', 'Young'], ['Weak', 'Strong'], ['Safe', 'Dangerous'],
  ['Casual', 'Formal'], ['Common', 'Rare'], ['Healthy', 'Unhealthy'], ['Relaxing', 'Stressful'],
  ['Indoor', 'Outdoor'], ['Practical', 'Impractical'], ['Serious', 'Silly'], ['Modern', 'Old-fashioned'],
  ['Niche', 'Mainstream'], ['Subtle', 'Obvious'], ['Comfortable', 'Uncomfortable'], ['Realistic', 'Unrealistic'],
  ['Cheap Date', 'Expensive Date'], ['Bad Superpower', 'Good Superpower'], ['Guilty Pleasure', 'Genuinely Good'],
  ['Underdog', 'Favorite'], ['Sweet', 'Savory'], ['Introvert Activity', 'Extrovert Activity'],
  ['Low Effort', 'High Effort'], ['Predictable', 'Surprising'], ['Wholesome', 'Chaotic'],
  ['Timeless', 'Trendy'], ['Solo Activity', 'Group Activity'], ['Not a Vacation', 'Dream Vacation'],
  ['Bad First Date', 'Great First Date'], ['Forgettable', 'Iconic'], ['Overhyped Movie', 'Underhyped Movie'],
  ['Should Be Illegal', 'Should Be Required'], ['Waste of Money', 'Worth Every Penny'],
  ['Petty', 'Justified'], ['Basic', 'Unique'], ['Annoying', 'Endearing'], ['Bad Roommate Habit', 'Fine Habit'],
  ['Terrible Superhero Name', 'Great Superhero Name'], ['Bad Pizza Topping', 'Great Pizza Topping'],
  ['Unimpressive Talent', 'Impressive Talent'], ['Bad Career Choice', 'Great Career Choice'],
  ['Awkward Small Talk', 'Great Conversation'], ['Overpacked Suitcase', 'Perfectly Packed'],
  ['Bad Band Name', 'Great Band Name'], ['Too Spicy', 'Not Spicy Enough'], ['Cluttered', 'Minimalist'],
  ['Bad Tattoo Idea', 'Great Tattoo Idea'], ['Skippable Movie Sequel', 'Must-Watch Sequel'],
  ['Not a Party Game', 'Perfect Party Game'], ['Low Stakes', 'High Stakes'], ['Forgivable', 'Unforgivable'],
  ['Bad Icebreaker', 'Great Icebreaker'], ['Nostalgic', 'Forward-looking'], ['Underpaid Job', 'Overpaid Job'],
  ['Too Short', 'Too Long'], ['Bad Excuse', 'Good Excuse'], ['Overplanned', 'Spontaneous'],
  ['Not Instagrammable', 'Very Instagrammable'], ['Bad Gift', 'Great Gift'], ['Villain Behavior', 'Hero Behavior'],
  ['Low Budget Movie', 'Blockbuster'], ['Bad Nickname', 'Great Nickname'], ['Impulsive', 'Calculated'],
  ['Should Stay a Secret', 'Should Be Shared'], ['Underdog Sport', 'Popular Sport'],
  ['Bad Roommate', 'Great Roommate'], ['Generic', 'Distinctive'], ['Local', 'Global'],
  ['Indoorsy', 'Outdoorsy'], ['Bad App Idea', 'Great App Idea'], ['Overrated Vacation Spot', 'Underrated Vacation Spot'],
  ['Unnecessary Gadget', 'Essential Gadget'], ['Bad Habit', 'Good Habit'], ['Too Formal', 'Too Casual'],
  ['Forgettable Meal', 'Memorable Meal'], ['Petty Argument', 'Serious Argument'], ['Overdone Trend', 'Fresh Trend'],
  ['Bad Roommate Rule', 'Fair Roommate Rule'], ['Not Worth the Hype', 'Worth the Hype'],
  ['Cheap Thrill', 'Genuine Achievement'], ['Bad Compliment', 'Great Compliment'],
  ['Unremarkable City', 'Iconic City'], ['Bad Wedding Gift', 'Great Wedding Gift'],
  ['Weird Flex', 'Impressive Flex'], ['Bad Life Advice', 'Great Life Advice'],
  ['Not a Hill to Die On', 'Hill to Die On'], ['Bad Roommate Story', 'Great Roommate Story'],
  ['Too Niche', 'Too Broad'], ['Bad Start to the Day', 'Great Start to the Day'],
  ['Skippable Chapter', 'Essential Chapter'], ['Unremarkable', 'Legendary'],
  ['Bad Party Trick', 'Great Party Trick'], ['Too Predictable', 'Too Random'],
];
