// Original, PG-13, workplace-appropriate prompt/answer cards written for
// this project, no official Cards Against Humanity text, to sidestep any
// licensing question on a public repo.

export const BLACK_CARDS: string[] = [
  "The secret to a great first date? _____.",
  "I got fired for _____.",
  "What's the real reason dinosaurs went extinct? _____.",
  "My therapist says I need to work on _____.",
  "The next Olympic sport: _____.",
  "What ruined the office party? _____.",
  "My horoscope this week: 'Beware of _____.'",
  "The new Netflix show everyone's binge-watching: _____.",
  "Grandma's secret ingredient is _____.",
  "The last thing I expected to find in my car was _____.",
  "Instead of a wedding, they had _____.",
  "The DMV now requires _____ before renewing your license.",
  "My roommate's excuse for not doing dishes: _____.",
  "Scientists just discovered _____ on Mars.",
  "The worst gift I ever received was _____.",
  "The new company slogan: 'We put the ___ in _____.'",
  "What's missing from my resume? _____.",
  "The true cause of climate change: _____.",
  "My New Year's resolution: more _____.",
  "The airline's new in-flight entertainment: _____.",
  "Instead of therapy, I just do _____.",
  "The city council's new plan to fix traffic: _____.",
  "My yoga instructor told me to visualize _____.",
  "The banned Olympic move: _____.",
  "What's really inside Area 51? _____.",
  "The new required class in school: _____.",
  "My phone autocorrected 'meeting' to _____.",
  "The zoo's newest exhibit: _____.",
  "The real reason I'm late: _____.",
  "The startup's pitch: 'It's like Uber, but for _____.'",
  "The wedding vow nobody expected: '_____, till death do us part.'",
  "What I brought to the potluck: _____.",
  "The app that finally solved dating: _____.",
  "My fortune cookie said: 'Beware of _____.'",
  "The new Olympic mascot: _____.",
  "The reason the flight was delayed: _____.",
  "My password hint is literally just _____.",
  "The office holiday party theme: _____.",
  "The reason my dog is in therapy: _____.",
  "The best way to survive a family reunion: _____.",
  "The new subscription box everyone wants: a monthly box of _____.",
  "The reason the meeting ran two hours long: _____.",
  "My love language is _____.",
  "The billboard on the highway just said _____.",
  "The new reality show: 'Real Housewives of _____.'",
  "What finally broke the internet: _____.",
  "The graduation speech nobody asked for: about _____.",
  "The reason the printer is broken again: _____.",
  "My gym added a new class: _____.",
  "The conspiracy theory that's actually true: _____.",
  "The last words of my houseplant: '_____.'",
  "What I actually do at work all day: _____.",
  "The self-help book that changed my life: '_____.'",
  "The new ride at the theme park: _____.",
  "My group chat has been arguing about _____ for three days.",
  "The reason the Wi-Fi is down: _____.",
  "The next big food trend: _____.",
  "My alarm clock now yells '_____' every morning.",
  "The reason we can't have nice things: _____.",
  "The museum's newest, most confusing exhibit: _____.",
  "The real MVP of the office is _____.",
];

export const WHITE_CARDS: string[] = [
  'A haunted vending machine', 'Aggressively competitive board games', 'An unexplainable smell', 'A raccoon in a tiny hat',
  'Three hours of uninterrupted silence', 'A well-timed dad joke', 'My browser history', 'A suspicious amount of confidence',
  'Interpretive dance', 'A group chat that never sleeps', 'Unsolicited life advice', 'A rogue Roomba',
  'The five stages of grief, but for Wi-Fi', 'A minor identity crisis', 'Competitive stretching', 'A very long sigh',
  'Emotional support snacks', 'An awkward silence that lasts too long', 'A karaoke machine nobody asked for', 'Professional overthinking',
  'A suspiciously specific horoscope', 'A committee meeting about the committee', 'Existential dread, lightly seasoned', 'A haunted printer',
  'The last slice of pizza', 'An overachieving houseplant', 'A conspiracy involving pigeons', 'Passive-aggressive sticky notes',
  'A three-hour nap disguised as "resting my eyes"', 'A very confident goldfish', 'An unhinged group project', 'Mandatory fun',
  'A vague sense of impending doom', 'The office microwave', 'A too-honest fortune cookie', 'An extremely judgmental cat',
  'Aggressive small talk', 'A spontaneous interpretive speech', 'Loudly narrating my every move', 'A single, dramatic tear',
  'An overly enthusiastic handshake', 'A suspiciously good deal', 'A parking spot with a personal vendetta', 'The last cookie in the jar',
  'An emotionally unavailable Roomba', 'A group hug nobody consented to', 'An unnecessarily long PowerPoint', 'A rebellious Alexa',
  'Competitive napping', 'A single sock, forever lost', 'A very literal genie', 'An overqualified barista',
  'A wildly inappropriate ringtone', 'The last Wi-Fi bar', 'A too-honest performance review', 'A rogue shopping cart',
  'An overzealous life coach', 'A cursed group project partner', 'The sound a printer makes right before it dies', 'A suspiciously calm dentist',
  'An unsolicited TED talk', 'A dramatic reading of the terms and conditions', 'A gym membership I never use', 'The last email of the day',
  'A haunted Zoom call', 'An overly literal genie', 'A suspiciously good Wi-Fi password', 'A committee formed to discuss forming a committee',
  'A very passive-aggressive email sign-off', 'An emotionally invested weather app', 'A too-honest résumé', 'A raccoon with a briefcase',
  'The seventh cup of coffee', 'An unnecessarily dramatic exit', 'A suspiciously well-timed fire alarm', 'A group chat typo that changed everything',
  'An overconfident Roomba', 'A single, defiant French fry', 'A too-literal life hack', 'The last piece of cake, hidden in the back of the fridge',
  'An emotionally exhausting board game night', 'A haunted office chair', 'A very specific type of chaos', 'An unreasonably loud yawn',
  'A group project that peer-reviews itself into oblivion', 'A suspiciously polite spam email', 'An overachieving to-do list', 'The last good parking spot',
  'A dramatic monologue delivered to a houseplant', 'An emotionally supportive stapler', 'A too-honest weather forecast', 'A rogue autocorrect',
  'The nine stages of assembling furniture', 'An unnecessarily competitive game of tag', 'A suspiciously self-aware chatbot', 'The last slice of the good bread',
  'An overly dramatic exit from a group chat', 'A committee dedicated to naming the committee', 'A too-honest fortune teller', 'An emotionally unavailable vending machine',
  'A single, triumphant sneeze', 'The last good Wi-Fi signal on a road trip', 'An unreasonably confident houseplant', 'A haunted office thermostat',
  'A dramatic reading of a grocery list', 'The nine lives of a very unbothered cat', 'An unsolicited group hug', 'A suspiciously specific alibi',
  'A too-honest group project evaluation', 'The last cookie, guarded fiercely', 'An emotionally exhausting family group chat', 'A raccoon running for office',
  'A too-literal metaphor', 'An unreasonably dramatic weather warning', 'The seventh consecutive rewatch of the same show', 'A suspiciously well-behaved toddler',
  'An overachieving alarm clock', 'A committee about committees about committees', 'The last good parking spot, fought for valiantly', 'A too-honest tarot reading',
  'An emotionally supportive houseplant', 'A rogue shopping cart with a mind of its own', 'The nine circles of assembling IKEA furniture', 'A suspiciously calm fire drill',
  'A dramatic exit set to imaginary music', 'An overqualified mall Santa', 'The last slice of pizza, fiercely contested', 'A too-honest office icebreaker',
  'An unreasonably confident weather app', 'A committee formed to disband the committee', 'The seventh cup of coffee, against doctor\'s orders', 'A suspiciously good alibi involving a raccoon',
  'An emotionally exhausting game night', 'A too-literal genie granting a very specific wish', 'The last good parking spot, defended with honor', 'A dramatic monologue about the printer',
];
